### ISSUE TITLE
alembic migration has error if starts from empty database

### ISSUE THREAD

**Issue by andrea-w-wang** [disinfoRG/ArticleParser#35]
I created a new and empty database at local and did migration. However, the process has the following error at step `Running upgrade 5b422bafbebf -> c68f35739c74, producer use uuid`: 

```
Traceback (most recent call last):
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1171, 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 81, in <module>
    run_migrations_online()
  File "migrations/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/Users/wyw/Projects/ArticleParser/migrations/versions/c68f35739c74_producer_use_uuid.py", line 49, in upgrade
    "producer", "producer_id", autoincrement=False, existing_type=sa.Integer
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/ops.py", line 1779, in alter_column
    return operations.invoke(alt)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 56, in alter_column
    **operation.kw
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/ddl/mysql.py", line 100, in alter_column
    else existing_comment,
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1046, in _execute_ddl
    compiled,
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1171, 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead')
[SQL: ALTER TABLE producer MODIFY producer_id INTEGER NULL]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by pm5** [comment]
That's odd.  I tried it on an empty database but didn't see the error.  Which version of database are you using?  If it's some version of MySQL then this bug is legit since we expect people to deploy on either MySQL or MariabDB (our servers use MariaDB 10.3.22).

I did find the SQL migration that was raising the error in the above message and patched it.  Hopefully this fixes it.

**Comment by andrea-w-wang** [comment]
I'm using 8.0.18 MySQL Community Server - GPL (mysql from dockerhub). Just tried building from empty db again but still seeing a similar error: 

```
Traceback (most recent call last):
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1171, 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/config.py", line 551, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 81, in <module>
    run_migrations_online()
  File "migrations/env.py", line 75, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/Users/wyw/Projects/ArticleParser/migrations/versions/c68f35739c74_producer_use_uuid.py", line 67, in upgrade
    existing_type=BINARY(16),
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/ops.py", line 1779, in alter_column
    return operations.invoke(alt)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/operations/toimpl.py", line 56, in alter_column
    **operation.kw
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/ddl/mysql.py", line 71, in alter_column
    else existing_comment,
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1046, in _execute_ddl
    compiled,
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/wyw/.local/share/virtualenvs/ArticleParser-AiVAcBPX/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1171, 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead')
[SQL: ALTER TABLE producer CHANGE producer_uuid producer_id BINARY(16) NULL]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by bwlynch** [comment]
I also had this issue using mySQL 5.7.3 and was able to resolve it by adding `nullable=False` in several places to several of the migration files. It was a bit trial and error, but I can push the changes I made for review if that would be useful

**Comment by pm5** [comment]
That sounds great @bwlynch !

**Comment by bwlynch** [comment]
Thanks @pm5 ! Just created PR #41 with the additions that seemed to fix it

**Comment by pm5** [comment]
LGTM
